export const GET_RECIPE_START = "GET_RECIPE_START";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_FAIL = "GET_RECIPE_FAIL";

export const CREATE_RECIPE_START = "CREATE_RECIPE_START";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_FAIL = "CREATE_RECIPE_FAIL";

export const ONE_RECIPE_START = "ONE_RECIPE_START";
export const ONE_RECIPE_SUCCESS = "ONE_RECIPE_SUCCESS";
export const ONE_RECIPE_FAIL = "ONE_RECIPE_FAIL";